language: c
compiler:
  - gcc

env:
  global:
    # Cross compiler prefix
    - CROSS_PREFIX=""
    # Build architecture/debian arch
    - ARCH=""
    - DEBIAN_ARCH=""
    - PPA=""
    - PKGS=""

matrix:
  include:
    - env: ARCH="i386"
    - env: PPA="ppa:ubuntu-toolchain-r/test"
           CROSS_PREFIX="aarch64-linux-gnu-"
           ARCH="aarch64"
           DEBIAN_ARCH="arm64"
    - env: CROSS_PREFIX="arm-linux-gnueabihf-"
           ARCH="arm"
           DEBIAN_ARCH="armhf"
           PKGS="cpp-arm-linux-gnueabihf"
             
before_install:
  - : ${PPA:?"No PPA specified"} && sudo add-apt-repository -y ${PPA}
  - sudo apt-get update -qq
  - : ${PKGS:?"No pkgs needed"} && sudo apt-get install -qq ${PKGS}
script:
  - CROSS_PREFIX=${CROSS_PREFIX} ARCH=${ARCH} ./configure
  - make
